### ISSUE TITLE
Confirm action before deleting/removing an entry

### ISSUE THREAD

**Issue by Juliotati** [selfdevs/accountability-dashboard#85] opened 2022-02-13 03:47 UTC
#### 
![image](https://user-images.githubusercontent.com/59662912/153737705-7168b7e2-28a9-4b65-ac8f-59bee41a1cad.png)

**Comment by cchampou** [comment] 2022-02-14 08:32
Duplicate of #63

**Comment by cchampou** [comment] 2022-02-14 08:34
I'm closing this one, and referenced it in the other one ;)

**Closed as completed by cchampou** 2022-02-14 08:34 UTC
Labels: Beginner level, Feature request
